# NumPy
Anaconda automatically installs NumPy to your system. Here we present a quick introduction to it and have some exercises for you to get familiarize with it. This will be part of the assignment for Week-1.

Numpy works in arrays and is much faster than working with lists. If you want to get some idea of why, have a look at  [NumPy — Why is it so fast?](https://medium.com/swlh/numpy-why-is-it-so-fast-8087f4da4d79). You can call an array with numpy.array function and can create 0,1,2,3 or N-dimensional array.

In [2]:
import numpy as np

In [3]:
arr_1D = np.array([5,4,6,2,3,8])

In [4]:
arr_2D = np.array([[2,3,4],[5,6,7]])
arr_3D = np.array([[1,6,2,8],[5,4,6,2],[7,2,9,8]])

In [5]:
print(arr_2D[1])
print(arr_3D[0][3])

[5 6 7]
8


You can also access a part of array with the slicing notation which is of the form [start : end : step]. If you don't give any value for step it is automatically assumed to be 1. The result includes the start index, but excludes the end index. Be careful about the indexing being used.


In [6]:
arr_1D[1:4]

array([4, 6, 2])

In [7]:
arr_3D[0:3][1:3]

array([[5, 4, 6, 2],
       [7, 2, 9, 8]])

Here, we give some examples of numpy functions.

In [8]:
arr_2D.shape # returns the shape of an array which is the number of elements in each dimension.

(2, 3)

In [9]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2)) #joins the two arrays
print(arr)

[1 2 3 4 5 6]


In [10]:
np.split(arr_1D,3) #splits the array into 3

[array([5, 4]), array([6, 2]), array([3, 8])]

In [11]:
np.sort(arr_1D)

array([2, 3, 4, 5, 6, 8])

In [13]:
np.linspace(2, 3, num=5) #Return evenly spaced numbers over a specified interval.

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

There are many more useful numpy functions but you can easily look them up [w3schools](https://www.w3schools.com/python/numpy/) or [geeksforgeeks](https://www.geeksforgeeks.org/numpy-tutorial/). We encourage you to go through them and use google whenever you need any specific function. Now, we here are some questions for you to do which is part of you assignment for Week-1. You assignment should only contain functions which return the required output (Don't put any input by yourself. We'll test your code ourselves). Make a single jupyter notebook for both Matplotlib and NumPy assignment.

 1. Write a NumPy program to multiply two given arrays of same size element-by-element. 


 2. Write a NumPy program to reverse an array (first element becomes last).


 3. Write a NumPy program which will remove all the elements between 5 and 8.
 

4. Write a NumPy program for finding the determinant of the 3D input matrix.


 5. Write a NumPy program which swaps the two rows of 2D array.


 6. Write a NumPy program to find most frequent value in an array.